# Generated by Django 5.0.6 on 2024-10-12 05:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flights", "0002_flightsearchbreakdown_alter_flight_search_date_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FlightSearchCache",
        ),
        migrations.AlterField(
            model_name="flight",
            name="search_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 10, 12, 5, 23, 36, 406986, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="flightsearchbreakdown",
            name="search_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 10, 12, 5, 23, 36, 435387, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
