# Generated by Django 5.0.6 on 2024-11-04 03:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flights", "0006_alter_flight_search_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flight",
            name="search_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 11, 4, 3, 37, 59, 845057, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="flightsearchbreakdown",
            name="search_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 11, 4, 3, 37, 59, 859278, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="flightsearchcache",
            name="search_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 11, 4, 3, 37, 59, 859654, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
