# Generated by Django 5.0.6 on 2024-08-18 05:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Flight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("departure_text", models.CharField(max_length=4)),
                ("arrival_text", models.CharField(max_length=4)),
                ("departure_date", models.DateField()),
                ("return_date", models.DateField()),
                (
                    "search_date",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2024, 8, 18, 5, 56, 6, 461145, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FlightSearchCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query_hash", models.CharField(max_length=32, unique=True)),
                ("result_json", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
