# Generated by Django 5.0.6 on 2024-10-10 16:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FlightSearchBreakdown",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("departure_text", models.CharField(max_length=4)),
                ("arrival_text", models.CharField(max_length=4)),
                ("departure_date", models.DateField()),
                ("return_date", models.DateField()),
                (
                    "search_date",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2024,
                            10,
                            10,
                            16,
                            34,
                            50,
                            226224,
                            tzinfo=datetime.timezone.utc,
                        )
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="flight",
            name="search_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 10, 10, 16, 34, 50, 212763, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="flightsearchcache",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 10, 10, 16, 34, 50, 226564, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
