# Generated by Django 5.0.6 on 2024-10-12 05:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0003_delete_flightsearchcache_alter_flight_search_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FlightSearchCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("origin_code", models.CharField(max_length=4)),
                ("destination_code", models.CharField(max_length=4)),
                ("origin_depart_time", models.CharField(max_length=50)),
                ("destination_arrival_time", models.CharField(max_length=50)),
                ("duration", models.CharField(max_length=50)),
                ("main_cabin_min", models.CharField(max_length=50)),
                ("premium_cabin_min", models.CharField(max_length=50)),
                (
                    "search_date",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2024,
                            10,
                            12,
                            5,
                            24,
                            45,
                            897932,
                            tzinfo=datetime.timezone.utc,
                        )
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="flight",
            name="search_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 10, 12, 5, 24, 45, 869450, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="flightsearchbreakdown",
            name="search_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 10, 12, 5, 24, 45, 897504, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
